baseURL: https://himloul.github.io/
languageCode: en-us
title: Hamza's blog
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "Hamza's Blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: Hamza Imloul
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  hideFooter: true
  showtoc: false
  tocopen: false
  math: true
  comments: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "icons/favicon.ico"
    favicon16x16: "icons/favicon-16x16.png"
    favicon32x32: "icons/favicon-32x32.png"
    apple_touch_icon: "icons/apple-touch-icon.png"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Hamza's blog"
    icon: icons/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Hamza imloul
    subtitle: "Hello, my name is Hamza and I am keeping track of my learning progress and personal projects through this blog. Alongside creating content on ML, I also work as a **NLP engineer** and helping my team in Applied research and Data science."
    imageUrl: "profile.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "\U0001F44B Welcome to Hamza's blog"
    Content: Hello, my name is Hamza and I am currently keeping track of my learning progress and personal projects through this blog. Alongside creating content on ML, I also work as a NLP engineer and helping my team in Applied research and Data science [more about me **here**](/me/).

  socialIcons:
    - name: twitter
      url: "https://twitter.com/hamzaonde"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/himloul"
    - name: linkedin
      url: "https://www.linkedin.com/in/hamza-imloul"
    - name: mastodon
      url: "https://sigmoid.social/@himloul"
    - name: behance
      url: "https://www.behance.com/himloul"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/himloul/himblog/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 10

    - identifier: search
      name: Search
      url: /search/
      weight: 20

    - identifier: posts
      name: Posts
      url: /posts/
      weight: 30

    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30

    - identifier: about
      name: About
      url:  /me/
      weight: 40

    - identifier: sketches
      name: Sketches
      url:  /art/
      weight: 40

    - identifier: example
      name: LinkedIn
      url: https://www.linkedin.com/in/hamza-imloul/
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
    # hrefTargetBlank: true
